name    'example42-bundler'
version '2.0.12'
author  'Alessandro Franceschi'
license 'Apache2'
project_page 'http://www.example42.com'
source  'https://github.com/example42/puppet-bundler'
summary 'Puppet module for bundler'
description 'This module installs and manages bundler. Check README for details.'
dependency 'example42/puppi', '>= 2.0.0'
# dependency 'example42/ruby', '>= 2.0.0'
# dependency 'example42/monitor', '>= 2.0.0'
# dependency 'example42/firewall', '>= 2.0.0'
